### ISSUE TITLE
perm checking takes ALOT of time

### ISSUE THREAD

**Issue by ghost** [genboy/Festival#262] opened 2020-01-25 21:27 UTC
when i make an area use the player perms it takes him alot of time for the command to be executed and he has to like enter and leave enter and leave its just confusing and i couldn't find the exact way for it to work but if he is op it executes immediately, unlike if it wasn't on it executes immediately, and the area isn't big its around 14 blocks in total.

using version 2.1.0 master branch

**Comment by genboy** [comment] 2020-01-26 16:15
Hi @mote166 thank you for posting this problem, i'll try to reproduce this to find and fix the problem. Could u give me the used pocketmine version and a list of installed plugins? Just incase, to cross check some issues etc. Thank you!

**Comment by mote166** [comment] 2020-01-26 20:37
using pocketmine 3.11.3
plugins are private i can msg u them on any other account u provide

**Comment by mote166** [comment] 2020-01-30 09:56
any progress so far?

**Comment by genboy** [comment] 2020-01-30 14:56
Yeah, I found some incorrect variables in the code that should be adjusted, I will be on it next couple of days.

I also noticed this function is using pocketmine's PlayerCommandPreprocessEvent function. I suppose that function heavely relies on server and internet speed (preprocessing the event) vs a simple clientside variable defining the player as op, making the difference in execution time.
I'm not sure how many Festival users also have this problem, we should make it a good practice to also check the server CPU and memory while testing.

**Comment by mote166** [comment] 2020-02-12 02:59
u know this is an important issue for me i have alot of things to add but im waiting for this to get fixed in order for them to work properly

**Comment by genboy** [comment] 2020-02-12 20:15
Hi @mote166 could you test if the problem persists using [dev #115](https://poggit.pmmp.io/babs/1126e) or [dev #116](https://poggit.pmmp.io/babs/1134a)

**Comment by mote166** [comment] 2020-02-15 03:46
sorry for the late reply, yes issue still occur

**Comment by genboy** [comment] 2020-02-15 09:22
Hi @mote166 can see if the server cpu goes up when this happens?
Which permissions handling plugin is used in your setup?

**Comment by mote166** [comment] 2020-02-15 15:36
yes it was 7% and when players were inside the area trying to teleport it jumped to 14%

**Comment by mote166** [comment] 2020-02-15 15:36
i use pureperms latest version

**Comment by mote166** [comment] 2020-02-20 20:55
any updates?

**Comment by genboy** [comment] 2020-02-21 21:49
Hi @mote166, I've tested some combinations with pureperms and also had the cpu go up. 
Now a bit stuck looking into pureperms what code is combined and why it becomes laggy. 
To compare i should also test with some other permissionsplugin or native settings, if you can please do, then we can speed up the progress a bit, i'll be checking the other plugin code to compare.
Sorry i could not make much time for this lately, I will try to make time this month to solve this.

**Comment by mote166** [comment] 2020-02-24 01:47
sorry but i can't test other permission plugins since the server is public and people are on it 24/7

**Comment by genboy** [comment] 2020-11-01 16:09
Issue reporter missing, problem not confirmed or solved

**Closed by genboy** 2020-11-01 16:09 UTC
Labels: In progress
